### ekf config file ###
ekf_filter_node:
    ros__parameters:
# The frequency, in Hz, at which the filter will output a position estimate. Note that the filter will not begin
# computation until it receives at least one message from one of the inputs. It will then run continuously at the
# frequency specified here, regardless of whether it receives more measurements. Defaults to 30 if unspecified.
        frequency: 30.0
        
# ekf_localization_node and ukf_localization_node both use a 3D omnidirectional motion model. If this parameter is
# set to true, no 3D information will be used in your state estimate. Use this if you are operating in a planar
# environment and want to ignore the effect of small variations in the ground plane that might otherwise be detected
# by, for example, an IMU. Defaults to false if unspecified.
        two_d_mode: true

# Whether to publish the acceleration state. Defaults to false if unspecified.
        publish_acceleration: true

# Whether to broadcast the transformation over the /tf topic. Defaults to true if unspecified.
# When to Disable publish_tf
# You must set publish_tf to false if another part of your system is already publishing the 
# required transform to avoid TF conflicts, which are a major cause of robot "jumping" or errors like TF_OLD_DATA. 
# * Global EKF (Map Level): If you are using a second EKF instance for global localization 
# (fusing GPS or AMCL data) where the world_frame is set to map_frame (e.g., map), this instance 
# should not publish the map -> base_link transform directly. Instead, it publishes 
# a map -> odom transform, using the odom -> base_link transform provided by the local EKF instance.
# * External Odometry Source: In a simulation environment like Gazebo, the differential drive plugin 
# often publishes the odom -> base_link transform automatically. In this case, you would disable 
# the EKF's publish_tf and only use its filtered odometry data via the /odometry/filtered topic. 
        publish_tf: false
        
# 1. Set the map_frame, odom_frame, and base_link frames to the appropriate frame names for your system.
#     1a. If your system does not have a map_frame, just remove it, and make sure "world_frame" is set to the value of odom_frame.
# 2. If you are fusing continuous position data such as wheel encoder odometry, visual odometry, or IMU data, set "world_frame" 
#    to your odom_frame value. This is the default behavior for robot_localization's state estimation nodes.
# 3. If you are fusing global absolute position data that is subject to discrete jumps (e.g., GPS or position updates from landmark 
#    observations) then:
#     3a. Set your "world_frame" to your map_frame value
#     3b. MAKE SURE something else is generating the odom->base_link transform. Note that this can even be another state estimation node 
#         from robot_localization! However, that instance should *not* fuse the global data.
        map_frame: map              # Defaults to "map" if unspecified
        odom_frame: odom            # Defaults to "odom" if unspecified
        base_link_frame: base_footprint  # Defaults to "base_link" if unspecified
        world_frame: odom           # Defaults to the value of odom_frame if unspecified
        
        odom0: /wheel/odometry
        odom0_config: [true,  true,  true,      # x, y, z
                       false, false, false,     # roll, pitch, yaw
                       false, false, false,     # vx, vy, vz
                       false, false, true,      # vroll, vpitch, vyaw
                       false, false, false]     # ax, ay, az
        # If you have high-frequency data or are running with a low frequency parameter value, then you may want to increase
        # the size of the subscription queue so that more measurements are fused.
        # odom0_queue_size: 2
        
        # [ADVANCED] When measuring one pose variable with two sensors, a situation can arise in which both sensors under-
        # report their covariances. This can lead to the filter rapidly jumping back and forth between each measurement as they
        # arrive. In these cases, it often makes sense to (a) correct the measurement covariances, or (b) if velocity is also
        # measured by one of the sensors, let one sensor measure pose, and the other velocity. However, doing (a) or (b) isn't
        # always feasible, and so we expose the differential parameter. When differential mode is enabled, all absolute pose
        # data is converted to velocity data by differentiating the absolute pose measurements. These velocities are then
        # integrated as usual. NOTE: this only applies to sensors that provide pose measurements; setting differential to true
        # for twist measurements has no effect.
        ## odom0_differential: false
        
        # [ADVANCED] When the node starts, if this parameter is true, then the first measurement is treated as a "zero point"
        # for all future measurements. While you can achieve the same effect with the differential parameter, the key
        # difference is that the relative parameter doesn't cause the measurement to be converted to a velocity before
        # integrating it. If you simply want your measurements to start at 0 for a given sensor, set this to true.
        # odom0_relative: false

        # [ADVANCED] Whether to use the starting pose of child_frame_id as the origin of odometry.
        # Note: this is different from setting odom0_relative to true, as when child_frame is different from 
        # base_link_frame, the rotation of base_link will be coupled into the translation of child_frame.
        # Set to true for fusing secondary odometry sources that are rigidly connected to base_link but has a non-zero 
        # offset from base_link.
        # odom0_pose_use_child_frame: false

         # [ADVANCED] If your data is subject to outliers, use these threshold settings, expressed as Mahalanobis distances, to
        # control how far away from the current vehicle state a sensor measurement is permitted to be. Each defaults to
        # numeric_limits<double>::max() if unspecified. It is strongly recommended that these parameters be removed if not
        # required. Data is specified at the level of pose and twist variables, rather than for each variable in isolation.
        # For messages that have both pose and twist data, the parameter specifies to which part of the message we are applying
        # the thresholds.
        #odom0_pose_rejection_threshold: 5.0
        #odom0_twist_rejection_threshold: 1.0

        imu0: /imu/data
        imu0_config: [false, false, false,      # x, y, z
                true, true, true,               # roll, pitch, yaw
                false, false, false,            # vx, vy, vz
                true, true, true,               # vroll, vpitch, vyaw
                false, false, false]            # ax, ay, az


        imu0_differential: false
        imu0_relative: true

        # imu0_differential: false
        # imu0_relative: true
        # imu0_queue_size: 5
        # imu0_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
        # imu0_twist_rejection_threshold: 0.8                #
        # imu0_linear_acceleration_rejection_threshold: 0.8  #

        # [ADVANCED] Some IMUs automatically remove acceleration due to gravity, and others don't. If yours doesn't, please set
        # this to true, and *make sure* your data conforms to REP-103, specifically, that the data is in ENU frame.
        # imu0_remove_gravitational_acceleration: true

        # [ADVANCED]  The EKF and UKF models follow a standard predict/correct cycle. During prediction, if there is no
        # acceleration reference, the velocity at time t+1 is simply predicted to be the same as the velocity at time t. During
        # correction, this predicted value is fused with the measured value to produce the new velocity estimate. This can be
        # problematic, as the final velocity will effectively be a weighted average of the old velocity and the new one. When
        # this velocity is the integrated into a new pose, the result can be sluggish convergence. This effect is especially
        # noticeable with LIDAR data during rotations. To get around it, users can try inflating the process_noise_covariance
        # for the velocity variable in question, or decrease the  variance of the variable in question in the measurement
        # itself. In addition, users can also take advantage of the control command being issued to the robot at the time we
        # make the prediction. If control is used, it will get converted into an acceleration term, which will be used during
        # prediction. Note that if an acceleration measurement for the variable in question is available from one of the
        # inputs, the control term will be ignored.
        # Whether or not we use the control input during prediction. Defaults to false.
        # use_control: true

        

        # More parameters can be added here as needed, see details. https://github.com/cra-ros-pkg/robot_localization/blob/ros2/params/ekf.yaml
