/**:
  ros__parameters:
    # The name of the base frame of the robot. This is used for determining robot position on map. Mandatory.
    robot_base_frame: base_link
    # Specifies topic of source <<MsgLink(nav_msgs/OccupancyGrid)>>. Mandatory.
    costmap_topic: /global_costmap/costmap
    # Specifies topic of source <<MsgLink(map_msgs/OccupancyGridUpdate)>>. Not necessary if source of map is always publishing full updates, i.e. does not provide this topic.    
    costmap_updates_topic: /global_costmap/costmap_updates
    # Specifies whether or not publish visualized frontiers.
    visualize: true
    # Rate in Hz at which new frontiers will computed and goal reconsidered.
    # default = `1.0`
    planner_frequency: 0.5
    # Time in seconds. When robot do not make any progress for `progress_timeout`, current goal will be abandoned.
    # default = `30.0`
    progress_timeout: 320.0
    # Used for weighting frontiers. This multiplicative parameter affects frontier potential component of the frontier
    #  weight (distance to frontier).
    # default = `1e-3` 5.0
    # potential_scale: 0.0001
    #potential_scale: 0.1
    potential_scale: 1.0
    # Used for weighting frontiers. This multiplicative parameter affects frontier orientation component of the frontier weight. 
    # This parameter does currently nothing and is provided solely for forward compatibility.
    # default = `0`
    orientation_scale: 1.0
    # Treat frontier goals within this distance as the same goal to avoid
    # rapid retargeting when frontier centroids jitter with map updates.
    goal_aliasing_distance: 0.30
    # Used for weighting frontiers. This multiplicative parameter affects frontier gain component of 
    # the frontier weight (frontier size).
    # default = `1.0`
    gain_scale: 1.0
    # Transform tolerance to use when transforming robot pose.
    # default = `0.3`
    transform_tolerance: 0.3
    # Minimum size of the frontier to consider the frontier as the exploration goal. In meters.
    # default = `0.5`
    min_frontier_size: 0.02
    return_to_init: false

